mysite/urls.py
from django.contrib import admin
from django.urls import path

from core.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('send-email/', index, name='send_email')
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
# core/forms.py
from django import forms

class SendEmailForm(forms.Form):
    email = forms.EmailField()
    content = forms.CharField()

core/views.py
from django.shortcuts import render

from .forms import SendEmailForm
from .tasks import send_email_task
# Create your views here.

def index(request):
    if request.method == 'POST':
        form = SendEmailForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            content = form.cleaned_data['content']
            send_email_task.delay(email, content)
            return render(request, 'index.html', {'form': form})
    
    form = SendEmailForm()
    return render(request, 'index.html', {'form': form})

core/templates/index.html
<!-- core/templates/index.html -->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Django Celery</title>
  </head>
  <body>
    <div class="container mt-5">
      <form method='post'>
        {% csrf_token %}
        <p>Send email to: <input type="text" name="email" class="form-control" id="id_email" placeholder="Email"></p>
        <p>Content: <input type="text" name="content" class="form-control" id="id_content" placeholder="Please Enter the Content"></p>      
        <button type="submit" class="btn btn-primary">Send</button>
      </form>
    </div>
  </body>
</html>